version: '3.9' # Versão do docker
services: # Services do MySQL e Java
  db:
    image: mysql:8.0.29 # Versão do MySQL
    command: mysqld --default-authentication-plugin=mysql_native_password # Comando para se autenticar
    restart: always # Ele vai ficar se reiniciando até que esteja pronto
    environment:
      TZ: America/Sao_Paulo # Time Zone
      MYSQL_ROOT_PASSWORD: admin123 # Senha do root
      MYSQL_USER: docker  # Outro Usuário
      MYSQL_PASSWORD: admin123  # Senha para todos os usuários
      MYSQL_DATABASE: rest_with_spring_boot_erudio # Nome do database
      MYSQL_ROOT_HOST: '%'  # Permitir acesso a todos os host
      MYSQL_TCP_PORT: 3308 # A porta do MySQL
    ports:
      - 3308:3308 #Pota local e porta do container
    expose:
      - 3308 #Expondo a porta 3308
    networks:
      - erudio-networks #A network para se conectar
  rest-with-spring-boot-erudio:
    image: vinidesenvolvedor/rest-with-spring-boot-erudio #Nome do seu usuário do docker hub com o nome da aplicação
    restart: always
    build: ./ #Caminho para encontrar o Dockerfile
    working_dir: /app #Nome do diretório
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_erudio? useTimezone=true&serverTimezone=UTC #Variável de ambiente
      SPRING.DATASOURCE.USERNAME: root #Variável de ambiente
      SPRING.DATASOURCE.PASSWORD: admin123 #Variável de ambiente
    ports:
      - 80:80 #Pota local e porta do container
    command: mvn spring-boot:run  # Comando para subir a aplicação
    networks:
      - erudio-networks #A network para se conectar
    depends_on:
      - db # Dizendo que ele depende do db
networks:
  erudio-networks:
    driver: bridge