server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
file:
  upload-dir: /UploadDirJava
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: viniciuslemes10
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      show-sql: true
    # properties:
      # hibernate:
       #  dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true